google:
    login: ${GOOGLE_LOGIN}
    password: ${GOOGLE_PASSWORD}
    spreadsheetName: CallForPaper
    worksheetName: dev
    consumerKey: ${GOOGLE_CONSUMER_KEY}
    consumerSecret: ${GOOGLE_CONSUMER_SECRET}

email:
    smtphost: smtp.gmail.com
    smtpport: 587
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL_USERNAME}

webapp:
    dir: app
---
spring:
    profiles: development
google:
    worksheetName: dev
---
spring:
    profiles: production
google:
    worksheetName: prod
webapp:
    dir: dist
---
spring:
    profiles: test
google:
    worksheetName: test