google:
    login: ${GOOGLE_LOGIN}
    password: ${GOOGLE_PASSWORD}
    spreadsheetName: CallForPaper
    worksheetName: dev
    consumerKey: ${GOOGLE_CONSUMER_KEY}
    consumerSecret: ${GOOGLE_CONSUMER_SECRET}

email:
    smtpHost: smtp.gmail.com
    smtpPort: 587
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL_USERNAME}
---
spring:
    profiles: development
google:
    worksheetName: dev
---
spring:
    profiles: production
google:
    worksheetName: prod
---
spring:
    profiles: test
google:
    worksheetName: test